# Generated by Django 5.1.4 on 2025-08-21 09:11

import django.db.models.deletion
import wiki.modelfield
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explicit_title', models.CharField(blank=True, default='', max_length=255, verbose_name='title')),
                ('slug', models.SlugField(blank=True, db_index=False, unique=True, verbose_name='slug')),
                ('raw_content', models.TextField(verbose_name='content')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='order')),
                ('content_title', models.CharField(editable=False, max_length=255)),
                ('content_html', models.TextField(editable=False)),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='name')),
                ('content', wiki.modelfield.BinaryFileField(default=b'', verbose_name='content')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wiki.article', verbose_name='article')),
            ],
            options={
                'verbose_name': 'Attachment',
                'verbose_name_plural': 'Attachments',
                'unique_together': {('article', 'name')},
            },
        ),
    ]
