# Generated by Django 5.1.4 on 2025-04-03 12:13

import django.db.models.deletion
import ledger.modelfield
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('credit', ledger.modelfield.PositiveFixedPrecisionField(decimal_places=2, default=0)),
                ('member', models.BooleanField()),
                ('active', models.BooleanField(default=True)),
                ('permanent', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['group', 'name'],
                'permissions': [('add_permanent_account', 'Can add permanent accounts'), ('change_permanent_account', 'Can change permanent accounts')],
            },
        ),
        migrations.CreateModel(
            name='AccountGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AccountBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('closing_balance', ledger.modelfield.FixedPrecisionField(decimal_places=2)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='ledger.account')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='account',
            name='group',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ledger.accountgroup'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cost', ledger.modelfield.PositiveFixedPrecisionField(decimal_places=2)),
                ('member_cost', ledger.modelfield.PositiveFixedPrecisionField(blank=True, decimal_places=2)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('group', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ledger.productgroup')),
            ],
            options={
                'ordering': ['group', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', ledger.modelfield.FixedPrecisionField(decimal_places=2)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(max_length=255)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='ledger.account')),
                ('closing_balance', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='ledger.accountbalance')),
                ('issuer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('related_transaction', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ledger.transaction')),
            ],
            options={
                'permissions': [('add_custom_transaction', 'Can make arbitrary deposits and withdrawls'), ('add_permanent_custom_transaction', 'Can make arbitrary deposits and withdrawls for permanent accounts')],
            },
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(models.F('active'), models.OrderBy(models.F('group'), nulls_first=True), models.F('name'), name='idx_grouped_accounts'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(models.F('active'), name='idx_active_account'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(models.OrderBy(models.F('group'), nulls_first=True), models.F('order'), name='idx_grouped_products'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(models.F('closing_balance'), models.OrderBy(models.F('timestamp'), descending=True), name='idx_recent_transactions'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(models.F('closing_balance'), name='idx_balance_transaction'),
        ),
    ]
