# Generated by Django 5.1.4 on 2025-04-13 12:01

import django.db.models.deletion
import ledger.modelfield
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['group', 'name'], 'permissions': [('add_permanent_account', 'Can add permanent accounts'), ('change_permanent_account', 'Can change permanent accounts')], 'verbose_name': 'account', 'verbose_name_plural': 'accounts'},
        ),
        migrations.AlterModelOptions(
            name='accountbalance',
            options={'ordering': ['-timestamp'], 'verbose_name': 'account balance', 'verbose_name_plural': 'account balances'},
        ),
        migrations.AlterModelOptions(
            name='accountgroup',
            options={'ordering': ['order'], 'verbose_name': 'account group', 'verbose_name_plural': 'account groups'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['group', 'order'], 'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
        migrations.AlterModelOptions(
            name='productgroup',
            options={'ordering': ['order'], 'verbose_name': 'product group', 'verbose_name_plural': 'product groups'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'permissions': [('add_custom_transaction', 'Can make arbitrary deposits and withdrawls'), ('add_permanent_custom_transaction', 'Can make arbitrary deposits and withdrawls for permanent accounts')], 'verbose_name': 'transaction', 'verbose_name_plural': 'transactions'},
        ),
        migrations.AlterField(
            model_name='account',
            name='active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='account',
            name='credit',
            field=ledger.modelfield.PositiveFixedPrecisionField(decimal_places=2, default=0, verbose_name='credit'),
        ),
        migrations.AlterField(
            model_name='account',
            name='group',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ledger.accountgroup', verbose_name='group'),
        ),
        migrations.AlterField(
            model_name='account',
            name='member',
            field=models.BooleanField(verbose_name='member'),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='account',
            name='permanent',
            field=models.BooleanField(default=False, verbose_name='permanent'),
        ),
        migrations.AlterField(
            model_name='accountbalance',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='ledger.account', verbose_name='account'),
        ),
        migrations.AlterField(
            model_name='accountbalance',
            name='closing_balance',
            field=ledger.modelfield.FixedPrecisionField(decimal_places=2, verbose_name='closing balance'),
        ),
        migrations.AlterField(
            model_name='accountbalance',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='timestamp'),
        ),
        migrations.AlterField(
            model_name='accountgroup',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='accountgroup',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost',
            field=ledger.modelfield.PositiveFixedPrecisionField(decimal_places=2, verbose_name='cost'),
        ),
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ledger.productgroup', verbose_name='group'),
        ),
        migrations.AlterField(
            model_name='product',
            name='member_cost',
            field=ledger.modelfield.PositiveFixedPrecisionField(blank=True, decimal_places=2, verbose_name='member cost'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='productgroup',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='productgroup',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='ledger.account', verbose_name='account'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=ledger.modelfield.FixedPrecisionField(decimal_places=2, verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='closing_balance',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='ledger.accountbalance', verbose_name='closing balance'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='issuer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='issuer'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='reason',
            field=models.CharField(max_length=255, verbose_name='reason'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='related_transaction',
            field=models.OneToOneField(blank=True, default=None, help_text='Used to track and associate canceled transactions', null=True, on_delete=django.db.models.deletion.CASCADE, to='ledger.transaction', verbose_name='related transaction'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='timestamp'),
        ),
    ]
