# Generated by Django 5.1.4 on 2025-01-10 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_delete_transactionhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='type',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='TransactionType',
        ),
    ]
