# Generated by Django 5.1.4 on 2025-04-13 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_alter_account_options_alter_accountbalance_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'permissions': [('add_deposit_transaction', 'Can make arbitrary deposits'), ('add_permanent_deposit_transaction', 'Can make arbitrary deposits for permanent accounts'), ('add_withdraw_transaction', 'Can make arbitrary withdrawls'), ('add_permanent_withdraw_transaction', 'Can make arbitrary withdrawls for permanent accounts')], 'verbose_name': 'transaction', 'verbose_name_plural': 'transactions'},
        ),
    ]
