# Generated by Django 5.1.4 on 2025-01-11 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_remove_transaction_type_alter_transaction_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='active_member',
            new_name='member',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='balance',
        ),
        migrations.AddField(
            model_name='account',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='picture',
            field=models.ImageField(default=None, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='ledger.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='closing_balance',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='ledger.accountbalance'),
        ),
        migrations.AlterField(
            model_name='accountbalance',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='ledger.account'),
        ),
    ]
