# Generated by Django 5.1.4 on 2025-04-15 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_alter_transaction_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='visible',
            field=models.BooleanField(default=True, verbose_name='visible'),
        ),
    ]
