# Generated by Django 5.1.4 on 2025-01-21 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0004_rename_active_member_account_member_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='picture',
        ),
    ]
