# Generated by Django 5.1.4 on 2025-04-15 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0004_product_visible'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['group', 'display_name'], 'permissions': [('add_permanent_account', 'Can add permanent accounts'), ('change_permanent_account', 'Can change permanent accounts')], 'verbose_name': 'account', 'verbose_name_plural': 'accounts'},
        ),
        migrations.RemoveIndex(
            model_name='account',
            name='idx_grouped_accounts',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='name',
            new_name='display_name',
        ),
        migrations.AddField(
            model_name='account',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='full name'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(models.F('active'), models.OrderBy(models.F('group')), models.F('display_name'), name='idx_grouped_accounts'),
        ),
    ]
