# Generated by Django 5.1.4 on 2025-01-25 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0005_remove_product_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='related_transaction',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ledger.transaction'),
        ),
    ]
