# Generated by Django 5.1.4 on 2025-04-15 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0005_alter_account_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='display_name',
            field=models.CharField(max_length=255, verbose_name='display name'),
        ),
    ]
