# Generated by Django 5.1.4 on 2025-04-26 13:25

import django.db.models.deletion
import ledger.modelfield
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0006_alter_account_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountbalance',
            name='previous_balance',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='ledger.accountbalance', verbose_name='previous balance'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='extra',
            field=models.JSONField(default=dict, verbose_name='extra'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('DEPT', 'Deposit'), ('WDRW', 'Withdraw'), ('ORDR', 'Order'), ('RVDP', 'Revert-Deposit'), ('RVWD', 'Revert-Withdraw')], default='ORDR', max_length=4, verbose_name='type'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=ledger.modelfield.PositiveFixedPrecisionField(decimal_places=2, verbose_name='amount'),
        ),
    ]
