# Generated by Django 5.1.4 on 2025-04-26 13:26

from django.db import migrations

def classify_transaction_type(apps, schema_editor):
    Transaction = apps.get_model('ledger', 'Transaction')
    for transaction in Transaction.objects.all():
        if transaction.reason.startswith('Storno: '):
            if transaction.amount > 0:
                transaction.type = 'RVDP'
            else:
                transaction.type = 'RVWD'
        elif transaction.amount > 0:
            transaction.type = 'DEPT'
        elif '€' in transaction.reason:
            transaction.type = 'WDRW'
        else:
            transaction.type = 'ORDR'
        
        transaction.amount = abs(transaction.amount)
        transaction.save()

def declassify_transaction_type(apps, schema_editor):
    WITHDRAW = {'RVWD', 'WDRW', 'ORDR'}

    Transaction = apps.get_model('ledger', 'Transaction')
    for transaction in Transaction.objects.all():
        if transaction.type in WITHDRAW:
            transaction.amount = -transaction.amount
        transaction.type = 'ORDR'
        transaction.save()

class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0007_accountbalance_previous_balance_transaction_extra_and_more'),
    ]

    operations = [
        migrations.RunPython(classify_transaction_type, declassify_transaction_type)
    ]
