# Generated by Django 5.1.4 on 2025-02-04 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0008_accountgroup_productgroup_alter_account_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['group', 'name']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['group', 'order']},
        ),
    ]
