# Generated by Django 5.1.4 on 2025-05-08 16:58

import ledger.modelfield
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0008_transaction_set_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=ledger.modelfield.PositiveFixedPrecisionField(decimal_places=2, verbose_name='amount'),
        ),
    ]
