# Generated by Django 5.1.4 on 2025-05-08 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0009_alter_transaction_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='extra',
            field=models.JSONField(blank=True, default=dict, verbose_name='extra'),
        ),
    ]
