# Generated by Django 5.1.4 on 2025-02-10 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0010_alter_account_group_alter_product_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['group', 'name'], 'permissions': [('add_permanent', 'Can add permanent accounts'), ('delete_permanent', 'Can remove permanent accounts')]},
        ),
        migrations.AddField(
            model_name='account',
            name='permanent',
            field=models.BooleanField(default=False),
        ),
    ]
