# Generated by Django 5.1.4 on 2025-07-26 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0010_page'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Page',
        ),
        migrations.DeleteModel(
            name='ProjectUser',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='extra',
            field=models.JSONField(blank=True, default=dict, verbose_name='extra'),
        ),
    ]
