# Generated by Django 5.1.4 on 2025-07-31 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0011_delete_page_delete_projectuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('ATCL', 'Article'), ('STCK', 'Stock')], default='ATCL', max_length=4, verbose_name='category'),
        ),
        migrations.AddField(
            model_name='product',
            name='order_number',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='order number'),
        ),
    ]
