# Generated by Django 5.1.4 on 2025-07-31 19:42

from django.db import migrations, models


def assign_display_name(apps, schema_editor):
    Product = apps.get_model("ledger", "Product")
    for product in Product.objects.all():
        product.display_name = product.full_name
        product.save()

class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0011_product_category_product_order_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='full_name',
        ),
        migrations.AddField(
            model_name='product',
            name='display_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='display name'),
        ),
        migrations.RunPython(assign_display_name)
    ]
