# Generated by Django 5.1.4 on 2025-02-13 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0011_alter_account_options_account_permanent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['group', 'name'], 'permissions': [('add_permanent', 'Can add permanent accounts'), ('change_permanent', 'Can add permanent accounts')]},
        ),
    ]
