# Generated by Django 5.1.4 on 2025-07-31 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0012_rename_name_product_full_name_product_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('DEPT', 'Deposit'), ('WDRW', 'Withdraw'), ('ORDR', 'Order'), ('RVDP', 'Revert-Deposit'), ('RVWD', 'Revert-Withdraw')], max_length=4, verbose_name='Type'),
        ),
    ]
