# Generated by Django 5.1.4 on 2025-02-13 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0012_alter_account_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['group', 'name'], 'permissions': [('add_permanent', 'Can add permanent accounts'), ('change_permanent', 'Can change permanent accounts')]},
        ),
    ]
