# Generated by Django 5.1.4 on 2025-12-31 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0013_alter_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='display_name',
            field=models.CharField(blank=True, help_text='Used for display', max_length=255, verbose_name='display name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='full_name',
            field=models.CharField(help_text='Used in transactions', max_length=255, verbose_name='name'),
        ),
    ]
