# Generated by Django 5.1.4 on 2025-02-17 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0013_alter_account_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['group', 'name'], 'permissions': [('add_permanent_account', 'Can add permanent accounts'), ('change_permanent_account', 'Can change permanent accounts')]},
        ),
        migrations.AlterModelOptions(
            name='accountbalance',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'permissions': [('add_deposit_transaction', 'Can make deposits for temporary accounts'), ('add_permanent_deposit_transaction', 'Can make deposits for permanent accounts')]},
        ),
    ]
