# Generated by Django 6.0.1 on 2026-02-10 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0014_alter_product_display_name_alter_product_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountbalance',
            name='timestamp',
            field=models.DateTimeField(verbose_name='timestamp'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='closing_balance',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='ledger.accountbalance', verbose_name='closing balance'),
        ),
    ]
