# Generated by Django 5.1.4 on 2025-02-24 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0014_alter_account_options_alter_accountbalance_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'permissions': [('add_custom_transaction', 'Can make arbitrary deposits and withdrawls'), ('add_permanent_custom_transaction', 'Can make arbitrary deposits and withdrawls for permanent accounts')]},
        ),
    ]
