# Generated by Django 6.0.1 on 2026-05-02 17:34

import django.db.models.deletion
import ledger.modelfield
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0015_alter_accountbalance_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['group', 'display_name'], 'permissions': [('add_permanent_account', 'Can add permanent accounts'), ('change_permanent_account', 'Can change permanent accounts'), ('view_inactive_account', 'Can view inactive accounts')], 'verbose_name': 'account', 'verbose_name_plural': 'accounts'},
        ),
        migrations.AlterField(
            model_name='account',
            name='active',
            field=models.BooleanField(default=True, help_text='Controls visibility.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='account',
            name='credit',
            field=ledger.modelfield.PositiveFixedPrecisionField(blank=True, decimal_places=2, default=0, help_text='How much the account can go into debt.', verbose_name='credit'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='related_transaction',
            field=models.OneToOneField(blank=True, default=None, editable=False, help_text='Used to track and associate canceled transactions', null=True, on_delete=django.db.models.deletion.CASCADE, to='ledger.transaction', verbose_name='related transaction'),
        ),
    ]
