# Generated by Django 5.1.4 on 2025-02-24 16:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0015_alter_transaction_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(models.F('closing_balance'), models.OrderBy(models.F('timestamp'), descending=True), name='idx_recent_transactions'),
        ),
    ]
