# Generated by Django 6.0.1 on 2026-06-01 20:57

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0016_alter_account_options_alter_account_active_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='transaction',
            managers=[
                ('recent_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
