# Generated by Django 5.1.4 on 2025-02-24 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0016_transaction_idx_recent_transactions'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='account',
            index=models.Index(models.F('active'), models.F('group'), models.F('name'), name='idx_grouped_accounts'),
        ),
    ]
