# Generated by Django 5.1.4 on 2025-02-24 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0017_account_idx_grouped_accounts'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(models.F('group'), models.F('order'), name='idx_grouped_products'),
        ),
    ]
