# Generated by Django 6.0.1 on 2026-06-14 12:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ledger', '0017_alter_transaction_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='created',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='created'),
        ),
    ]
