# Generated by Django 5.1.4 on 2025-02-24 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0018_product_idx_grouped_products'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='account',
            name='idx_grouped_accounts',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='idx_grouped_products',
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(models.F('active'), models.OrderBy(models.F('group'), nulls_first=True), models.F('name'), name='idx_grouped_accounts'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(models.OrderBy(models.F('group'), nulls_first=True), models.F('order'), name='idx_grouped_products'),
        ),
    ]
