# Generated by Django 5.1.4 on 2025-02-25 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0019_remove_account_idx_grouped_accounts_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='account',
            index=models.Index(models.F('active'), name='idx_active_account'),
        ),
    ]
