# Generated by Django 5.1.4 on 2025-02-25 12:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0020_account_idx_active_account'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(models.F('closing_balance'), name='idx_balance_transaction'),
        ),
    ]
