# Generated by Django 5.1.4 on 2025-03-28 10:47

import ledger.modelfield
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0021_transaction_idx_balance_transaction'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='account',
            name='idx_grouped_accounts',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='idx_grouped_products',
        ),
        migrations.AlterField(
            model_name='account',
            name='credit',
            field=ledger.modelfield.PositiveFixedPrecisionField(decimal_places=2),
        ),
        migrations.AlterField(
            model_name='accountbalance',
            name='closing_balance',
            field=ledger.modelfield.FixedPrecisionField(decimal_places=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost',
            field=ledger.modelfield.PositiveFixedPrecisionField(decimal_places=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='member_cost',
            field=ledger.modelfield.PositiveFixedPrecisionField(decimal_places=2),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=ledger.modelfield.FixedPrecisionField(decimal_places=2),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(models.F('active'), models.OrderBy(models.F('group'), nulls_first=True), models.F('name'), name='idx_grouped_accounts'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(models.OrderBy(models.F('group'), nulls_first=True), models.F('order'), name='idx_grouped_products'),
        ),
    ]
