# Generated by Django 5.1.4 on 2025-03-31 20:17

import ledger.modelfield
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0023_alter_account_credit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='credit',
            field=ledger.modelfield.PositiveFixedPrecisionField(decimal_places=2, default=0),
        ),
        migrations.AlterField(
            model_name='accountbalance',
            name='closing_balance',
            field=ledger.modelfield.FixedPrecisionField(decimal_places=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost',
            field=ledger.modelfield.PositiveFixedPrecisionField(decimal_places=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='member_cost',
            field=ledger.modelfield.PositiveFixedPrecisionField(blank=True, decimal_places=2),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=ledger.modelfield.FixedPrecisionField(decimal_places=2),
        ),
    ]
