# Generated by Django 5.1.4 on 2025-08-19 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_projectuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AutoLogin',
        ),
    ]
