# Generated by Django 5.1.4 on 2025-11-22 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autologin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoLoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('new_session_id', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.CharField(max_length=1024)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='autologin',
            name='unique_autologin_rules',
        ),
        migrations.RemoveField(
            model_name='autologin',
            name='device',
        ),
        migrations.AddField(
            model_name='autologin',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='autologin',
            name='session_key',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='autologinhistory',
            name='login',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='autologin.autologin'),
        ),
    ]
