# Generated by Django 5.1.4 on 2025-12-31 14:24

import colorfield.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('blackbook', '0001_initial'), ('blackbook', '0002_recipegroup_recipe_group'), ('blackbook', '0003_alter_recipe_options'), ('blackbook', '0004_remove_recipestep_unit_recipegroup_order_and_more'), ('blackbook', '0005_alter_recipe_options_alter_recipegroup_options_and_more'), ('blackbook', '0006_ingredientcategory_dark_color_and_more')]

    dependencies = [
        ('ledger', '0013_alter_transaction_type'),
        ('ledger', '0014_alter_product_display_name_alter_product_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('dark_color', colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=25, null=True, samples=None, verbose_name='Dark Color')),
                ('light_color', colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=25, null=True, samples=None, verbose_name='Light Color')),
            ],
        ),
        migrations.CreateModel(
            name='PrepMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('icon', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='ServingGlass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('icon', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('category', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blackbook.ingredientcategory')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='order')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('method', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blackbook.prepmethod', verbose_name='method')),
                ('product', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ledger.product', verbose_name='Product')),
                ('serving_glass', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blackbook.servingglass', verbose_name='Glass')),
                ('group', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blackbook.recipegroup', verbose_name='group')),
            ],
            options={
                'ordering': ['group__order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RecipeStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='order')),
                ('amount', models.CharField(blank=True, default='', max_length=64, verbose_name='amount')),
                ('instruction', models.CharField(blank=True, max_length=255, verbose_name='instruction')),
                ('ingredient', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='blackbook.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='blackbook.recipe')),
            ],
            options={
                'ordering': ['recipe', 'order'],
                'indexes': [models.Index(models.F('recipe'), models.F('order'), name='idx_recipe_order')],
            },
        ),
    ]
