# Generated by Django 5.1.4 on 2025-10-21 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blackbook', '0002_recipegroup_recipe_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['group', 'name']},
        ),
    ]
