# Generated by Django 5.1.4 on 2025-11-24 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackbook', '0003_alter_recipe_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipestep',
            name='unit',
        ),
        migrations.AddField(
            model_name='recipegroup',
            name='order',
            field=models.PositiveIntegerField(blank=True, db_index=True, default=0, verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='recipestep',
            name='amount',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='amount'),
        ),
        migrations.DeleteModel(
            name='Unit',
        ),
    ]
