# Generated by Django 5.1.4 on 2025-11-24 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackbook', '0004_remove_recipestep_unit_recipegroup_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['group__order', 'name']},
        ),
        migrations.AlterModelOptions(
            name='recipegroup',
            options={'ordering': ['order']},
        ),
        migrations.AlterField(
            model_name='recipegroup',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='order'),
        ),
    ]
