# Generated by Django 5.1.4 on 2025-12-31 13:52

import colorfield.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackbook', '0005_alter_recipe_options_alter_recipegroup_options_and_more'),
        ('ledger', '0014_alter_product_display_name_alter_product_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientcategory',
            name='dark_color',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=25, null=True, samples=None, verbose_name='Dark Color'),
        ),
        migrations.AddField(
            model_name='ingredientcategory',
            name='light_color',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=25, null=True, samples=None, verbose_name='Light Color'),
        ),
        migrations.AddField(
            model_name='prepmethod',
            name='icon',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='servingglass',
            name='icon',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='group',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blackbook.recipegroup', verbose_name='group'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='method',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blackbook.prepmethod', verbose_name='method'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='product',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ledger.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='serving_glass',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blackbook.servingglass', verbose_name='Glass'),
        ),
    ]
