# Generated by Django 5.1.4 on 2026-01-10 16:56

import blackbook.models
import colorfield.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackbook', '0001_initial_squashed_0006_ingredientcategory_dark_color_and_more'),
        ('ledger', '0014_alter_product_display_name_alter_product_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('color', colorfield.fields.ColorField(default=blackbook.models.random_color, image_field=None, max_length=25, samples=None, verbose_name='Color')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'verbose_name': 'Ingredient', 'verbose_name_plural': 'Ingredients'},
        ),
        migrations.AlterModelOptions(
            name='ingredientcategory',
            options={'verbose_name': 'Ingredient category', 'verbose_name_plural': 'Ingredient categories'},
        ),
        migrations.AlterModelOptions(
            name='prepmethod',
            options={'verbose_name': 'Prep method', 'verbose_name_plural': 'Prep methods'},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['group__order', 'name'], 'verbose_name': 'Recipe', 'verbose_name_plural': 'Recipes'},
        ),
        migrations.AlterModelOptions(
            name='recipegroup',
            options={'ordering': ['order'], 'verbose_name': 'Recipe Group', 'verbose_name_plural': 'Recipe Groups'},
        ),
        migrations.AlterModelOptions(
            name='recipestep',
            options={'ordering': ['recipe', 'order'], 'verbose_name': 'Recipe step', 'verbose_name_plural': 'Recipe steps'},
        ),
        migrations.AlterModelOptions(
            name='servingglass',
            options={'verbose_name': 'Serving glass', 'verbose_name_plural': 'Serving glasses'},
        ),
        migrations.AlterField(
            model_name='recipe',
            name='product',
            field=models.ForeignKey(blank=True, default=None, help_text='Used to display pricing', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ledger.product', verbose_name='Product'),
        ),
    ]
