# Generated by Django 5.1.4 on 2026-01-10 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackbook', '0007_tag_alter_ingredient_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(to='blackbook.tag'),
        ),
    ]
